version: '3.8'

services:
  web-service:
    build: .             # <--- Changed from ./app to .
    container_name: node-app
    restart: always
    expose:
      - "3000"

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-service